Repository OpenVoiceOS/ovos-audio, pull requests merged in 2023-10, with the labels that each got.

#27 feat/dialog_transformers
  .gitignore
  ovos_audio/playback.py
  ovos_audio/service.py
  ovos_audio/transformers.py
  requirements.txt
Labels: enhancement

#28 hotfix/plugin config loading
  ovos_audio/__main__.py
  ovos_audio/service.py
  ovos_audio/transformers.py
  requirements.txt
Labels: bug

#29 fix/playback thread
  ovos_audio/playback.py
  ovos_audio/service.py
  requirements.txt
Labels: bug

#30 feat/skip_skills_in_dialog_transform
  ovos_audio/service.py
  ovos_audio/transformers.py
Labels: enhancement

#34 feat/handle_hex_audiodata
  ovos_audio/service.py
Labels: enhancement

#38 Move plugins to extra dependencies and update documentation
  README.md
  requirements.txt
  requirements/extras.txt
  requirements/requirements.txt
  setup.py
Labels: packaging
